/*
  Auto-generated by Spline
*/
import * as THREE from 'three'
import { useRef, useState } from 'react'
import useSpline from '@splinetool/r3f-spline'
import { Clone, Float, Html, PerspectiveCamera } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import { animated } from '@react-spring/three'
import { Hoverable } from './Hoverable'
import { Text } from './TextFloat'

const topTargetPosition = new THREE.Vector3(0, -10, -211)
export default function Scene({ scroll, ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/Ja5cQsz5zoyoIvUL/scene.splinecode')

  // will be used to set the text to show when clicked
  const [showFrogTxt, setFrogTxt] = useState(false)
  const [showSmallFrogTxt, setSmallFrogTxt] = useState(false)
  const [showFishTxt, setFishTxt] = useState(false)
  const [showFishTxt2, setFishTxt2] = useState(false)

  const top = useRef()
  const sceneContent = useRef()
  const size = useThree((state) => state.size)
  const isMobile = size.width < -1140
  const lerpedScroll = useRef(0)

  useFrame(() => {
    // lerp the scroll
    lerpedScroll.current += (scroll.current - lerpedScroll.current) * 0.9

    // animate the camera
    const zStart = isMobile ? 1000 : 2100 // negative value means itll start facing back
    const zEnd = isMobile ? -2500 : -4140
    const xMin = isMobile ? 6000 : -8000 // the lowest point itll go to
    const xMax = isMobile ? -1200 : 4200
    const targetX = isMobile ? 5000 : 3
    const yBase = isMobile ? 600 : 2000 //height of camera, and will end at
    const yRange = isMobile ? -700 : -2700 //height it will dip to in transition, will always face end destination

    const t = lerpedScroll.current
    const arc = Math.sin(t * Math.PI)
    top.current.position.set(THREE.MathUtils.lerp(xMax, xMin, arc), arc * yRange + yBase, THREE.MathUtils.lerp(zStart, zEnd, t))
    topTargetPosition.x = THREE.MathUtils.lerp(0, targetX, arc)
    top.current.lookAt(topTargetPosition)
  })

  return (
    <>
      <color attach="background" args={['#445e83']} />
      <fog attach="fog" args={['#445e83', 4000, 8500]} />

      <animated.group {...props} dispose={null}>
        <PerspectiveCamera
          ref={top} //-- ref allows for the camera path to be used
          makeDefault={true}
          far={16000}
          near={5}
          fov={30}
          scale={1}
        />

        <group ref={sceneContent}>
          <mesh
            name="Rectangle 7"
            geometry={nodes['Rectangle 7'].geometry}
            material={materials.glass}
            receiveShadow
            position={[-703.46, -440.68, 6662.32]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={1}
          />

          <group position={[-113.38, 146.15, 257.02]}>
            <Html>
              <Text show={showFrogTxt}> Hi, Im George! unfortunately I have lost my prized possession my pearl. </Text>
            </Html>
          </group>

          <group position={[-2401.43, -828.97, -1349.6]}>
            <Html>
              <Text show={showFishTxt}> I think the pearl could be under a rock... </Text>
            </Html>
          </group>

          <group position={[-509.88, -197.25, 361.67]}>
            <Html>
              <Text show={showFishTxt2}> you might need to dive underwater to find it George! </Text>
            </Html>
          </group>

          <group position={[375.25, -16.31, -1245.76]}>
            <Html>
              <Text show={showSmallFrogTxt}> Thanks Dad, I really appreciate the gift! </Text>
            </Html>
          </group>

          <group>
            <Hoverable // Will move when hovered over, and display text on click
              onClick={() => {
                setFishTxt(!showFishTxt)
              }}>
              <Clone object={nodes['fish Instance 4']} />
            </Hoverable>

            <Hoverable
              onClick={() => {
                setFishTxt2(!showFishTxt2)
              }}>
              <Float>
                <Clone object={nodes['fish Instance']} />
              </Float>
            </Hoverable>

            <Hoverable
              onClick={() => {
                setFrogTxt(!showFrogTxt)
              }}>
              <Clone object={nodes[' frog']} />
            </Hoverable>

            <Hoverable
              onClick={() => {
                setSmallFrogTxt(!showSmallFrogTxt)
              }}>
              <Clone object={nodes[' frog 2']} />
            </Hoverable>

            <Hoverable onClick={() => {}}>
              <Clone object={nodes['Sphere 19']} />
            </Hoverable>

            <Hoverable onClick={() => {}}>
              <Clone object={nodes['Sphere 125']} />
            </Hoverable>

            <Hoverable onClick={() => {}}>
              <Clone object={nodes['Sphere 20']} />
            </Hoverable>
          </group>
<group>
          <Clone object={nodes['Rectangle 8']} />
          <Clone object={nodes['Text 2']} />
          <Clone object={nodes['Text 3']} />
          <Clone object={nodes['Text 4']} />
          </group>

          <mesh
            name="Rectangle 6"
            geometry={nodes['Rectangle 6'].geometry}
            material={materials.glass}
            castShadow
            receiveShadow
            position={[-817.37, -152.96, 177.28]}
            rotation={[Math.PI / 2, 0, -1.54]}
          />

          <mesh
            name="Rectangle 10"
            geometry={nodes['Rectangle 10'].geometry}
            material={materials['']}
            castShadow
            receiveShadow
            position={[-584.4, -152, -2269.1]}
            rotation={[-Math.PI / 2, 0, -1.57]}
            scale={1}
          />

          <mesh
            name="Ellipse 6"
            geometry={nodes['Ellipse 6'].geometry}
            material={materials.blend}
            castShadow
            receiveShadow
            position={[-2900.67, -1392.34, -512.91]}
            rotation={[-Math.PI / 2, -0.02, -Math.PI / 2]}
            scale={1}
          />
          
          <group>
            <Float>
              <Clone object={nodes['fish Instance 3']} />
            </Float>

            <Float>
              <Clone object={nodes['fish Instance 5']} />
            </Float>

            <Float>
              <Clone object={nodes['fish Instance 2']} />
            </Float>

            <Float floatIntensity={1} speed={0.3}>
              <Clone object={nodes['Sphere 18']} />
            </Float>
          </group>

          <mesh
            name="Rectangle 9"
            geometry={nodes['Rectangle 9'].geometry}
            material={materials['Rectangle 9 Material']}
            castShadow
            receiveShadow
            position={[-826.18, -200.64, 236.96]}
            rotation={[-Math.PI / 2, 0, -1.61]}
            scale={1}
          />

          <mesh
            name="Sphere 11"
            geometry={nodes['Sphere 11'].geometry}
            material={materials.highlight}
            castShadow
            receiveShadow
            position={[-2430.84, -1051.34, 359.34]}
            rotation={[-1.55, -0.02, -2.01]}
            scale={1}
          />
          <mesh
            name="Shape 9"
            geometry={nodes['Shape 9'].geometry}
            material={materials.sand}
            castShadow
            receiveShadow
            position={[-306.14, -939.82, 680.37]}
            rotation={[-Math.PI / 2, 0, 2.31]}
            scale={0.54}
          />
          <mesh
            name="Shape 18"
            geometry={nodes['Shape 18'].geometry}
            material={materials.sand}
            castShadow
            receiveShadow
            position={[-4673.37, -1412.93, -1904.4]}
            rotation={[-Math.PI / 2, -0.01, -1.57]}
            scale={0.54}
          />
          <mesh
            name="Shape 11"
            geometry={nodes['Shape 11'].geometry}
            material={materials.sand}
            castShadow
            receiveShadow
            position={[-2368.97, -1116.25, 3.42]}
            rotation={[-1.55, -0.01, -2.01]}
            scale={0.54}
          />
          <mesh
            name="Shape 10"
            geometry={nodes['Shape 10'].geometry}
            material={materials.sand}
            castShadow
            receiveShadow
            position={[-1367.48, -984.3, -854.04]}
            rotation={[-Math.PI / 2, 0, -2.01]}
            scale={0.54}
          />
          <mesh
            name="Shape 91"
            geometry={nodes['Shape 91'].geometry}
            material={materials.sand}
            castShadow
            receiveShadow
            position={[-1167.5, -931.35, -366.64]}
            rotation={[-Math.PI / 2, 0, -0.61]}
            scale={0.54}
          />
          <mesh
            name="Sphere 7"
            geometry={nodes['Sphere 7'].geometry}
            material={materials.sand}
            castShadow
            receiveShadow
            position={[116.66, -948.74, -505.83]}
            rotation={[-Math.PI / 2, 0, -1.62]}
            scale={0.54}
          />
          <mesh
            name="Sphere 10"
            geometry={nodes['Sphere 10'].geometry}
            material={materials.sand}
            castShadow
            receiveShadow
            position={[-2555.56, -1111.11, -509.13]}
            rotation={[-Math.PI / 2, 0, -2.23]}
            scale={0.54}
          />
          <mesh
            name="Sphere 9"
            geometry={nodes['Sphere 9'].geometry}
            material={materials.sand}
            castShadow
            receiveShadow
            position={[-2042.39, -910.17, 596.57]}
            rotation={[-Math.PI / 2, 0, -1.62]}
            scale={0.54}
          />
          <mesh
            name="Sphere 71"
            geometry={nodes['Sphere 71'].geometry}
            material={materials.sand}
            castShadow
            receiveShadow
            position={[-263.43, -910.17, 371]}
            rotation={[-Math.PI / 2, 0, -1.62]}
            scale={0.54}
          />
          <mesh
            name="Sphere 15"
            geometry={nodes['Sphere 15'].geometry}
            material={nodes['Sphere 15'].material}
            castShadow
            receiveShadow
            position={[-2626.73, -57.22, -119.44]}
            rotation={[Math.PI, 0.7, -Math.PI]}
            scale={0.54}
          />

          <mesh
            name="Sphere 11"
            geometry={nodes['Sphere 11'].geometry}
            material={materials.highlight}
            castShadow
            receiveShadow
            position={[391.46, -64.17, -1388.95]}
            rotation={[-1.55, -0.02, -2.65]}
            scale={1}
          />

          <mesh
            name="Sphere 135"
            geometry={nodes['Sphere 135'].geometry}
            material={nodes['Sphere 135'].material}
            castShadow
            receiveShadow
            position={[850.25, -1148.52, 1099.78]}
            rotation={[Math.PI, 1.25, -Math.PI]}
            scale={0.54}
          />
          <mesh
            name="Sphere 8"
            geometry={nodes['Sphere 8'].geometry}
            material={nodes['Sphere 8'].material}
            castShadow
            receiveShadow
            position={[-1716.72, -1083.02, -59.59]}
            rotation={[Math.PI, -1.06, Math.PI]}
            scale={0.54}
          />
          <mesh
            name="Sphere 72"
            geometry={nodes['Sphere 72'].geometry}
            material={nodes['Sphere 72'].material}
            castShadow
            receiveShadow
            position={[652.34, -958.33, 204.76]}
            scale={0.54}
          />
          <mesh
            name="Shape 145"
            geometry={nodes['Shape 145'].geometry}
            material={materials.seaweed}
            castShadow
            receiveShadow
            position={[-2668.38, -1229.14, 739.01]}
            rotation={[-Math.PI, 0.33, -Math.PI]}
            scale={0.54}
          />
          <mesh
            name="Shape 125"
            geometry={nodes['Shape 125'].geometry}
            material={materials.seaweed}
            castShadow
            receiveShadow
            position={[-2513.15, -1122.33, -485.9]}
            rotation={[-Math.PI, 0.61, -Math.PI]}
            scale={0.54}
          />
          <mesh
            name="Shape 92"
            geometry={nodes['Shape 92'].geometry}
            material={materials.seaweed}
            castShadow
            receiveShadow
            position={[-532.38, -912.75, -452.17]}
            rotation={[-Math.PI, 0.61, -Math.PI]}
            scale={0.54}
          />
          <mesh
            name="Shape 93"
            geometry={nodes['Shape 93'].geometry}
            material={materials.seaweed}
            castShadow
            receiveShadow
            position={[-267.94, -946.72, 447.7]}
            rotation={[0, 0.45, 0]}
            scale={0.54}
          />
          <mesh
            name="Shape 94"
            geometry={nodes['Shape 94'].geometry}
            material={materials.seaweed}
            castShadow
            receiveShadow
            position={[166.3, -930.44, -281.88]}
            rotation={[0, 0.45, 0]}
            scale={0.54}
          />
          <mesh
            name="Shape 135"
            geometry={nodes['Shape 135'].geometry}
            material={materials.seaweed}
            castShadow
            receiveShadow
            position={[-2578.63, -1137.62, 916.84]}
            rotation={[0, -1.56, 0]}
            scale={0.54}
          />
          <mesh
            name="Shape 95"
            geometry={nodes['Shape 95'].geometry}
            material={materials.seaweed}
            castShadow
            receiveShadow
            position={[-350.46, -931.19, 352.53]}
            scale={0.54}
          />
          <mesh
            name="Rectangle 3"
            geometry={nodes['Rectangle 3'].geometry}
            material={materials.sand}
            castShadow
            receiveShadow
            position={[-556.02, -1392.28, 57.56]}
            rotation={[-Math.PI / 2, 0, -1.62]}
            scale={0.54}
          />
          <mesh
            name="Rectangle 2"
            geometry={nodes['Rectangle 2'].geometry}
            material={materials.sand}
            castShadow
            receiveShadow
            position={[-355.21, -1127.53, -134.52]}
            rotation={[-Math.PI / 2, 0, -1.62]}
            scale={0.54}
          />
          <mesh
            name="Rectangle"
            geometry={nodes.Rectangle.geometry}
            material={materials.sand}
            castShadow
            receiveShadow
            position={[-285.05, -1017.53, 84.89]}
            rotation={[-Math.PI / 2, 0, -1.62]}
            scale={0.54}
          />
          <mesh
            name="Shape 5"
            geometry={nodes['Shape 5'].geometry}
            material={materials['front grass']}
            castShadow
            receiveShadow
            position={[-620.54, -136.08, -598.24]}
          />
          <mesh
            name="Shape 4"
            geometry={nodes['Shape 4'].geometry}
            material={materials['front grass']}
            castShadow
            receiveShadow
            position={[-486.34, -161.06, -391.57]}
          />
          <mesh
            name="Ellipse"
            geometry={nodes.Ellipse.geometry}
            material={materials.pond}
            castShadow
            receiveShadow
            position={[-836.15, -160.77, 433.21]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={1}
          />
          <mesh
            name="Shape 15"
            geometry={nodes['Shape 15'].geometry}
            material={materials['front grass']}
            castShadow
            receiveShadow
            position={[-1071.04, -132.67, -174.73]}
            rotation={[0, 0.91, 0]}
          />
          <mesh
            name="Cylinder 6"
            geometry={nodes['Cylinder 6'].geometry}
            material={materials['lily pad']}
            castShadow
            receiveShadow
            position={[-397.12, -154.98, -341.55]}
            scale={2}
          />
          <mesh
            name="Shape 16"
            geometry={nodes['Shape 16'].geometry}
            material={materials['back grass']}
            castShadow
            receiveShadow
            position={[-886.68, -119.11, -1111.28]}
          />
          <mesh
            name="Shape 17"
            geometry={nodes['Shape 17'].geometry}
            material={materials['back grass']}
            castShadow
            receiveShadow
            position={[-2290.19, -124.41, -957.64]}
          />
          <mesh
            name="Shape"
            geometry={nodes.Shape.geometry}
            material={materials['back grass']}
            castShadow
            receiveShadow
            position={[-714.41, -145.41, -700.51]}
          />
          <mesh
            name="Sphere 16"
            geometry={nodes['Sphere 16'].geometry}
            material={materials.firefly}
            castShadow
            receiveShadow
            position={[-214.99, 2.44, 507.65]}
          />

          <mesh
            name="Sphere 5"
            geometry={nodes['Sphere 5'].geometry}
            material={materials.firefly}
            castShadow
            receiveShadow
            position={[217.26, -2.51, -49.61]}
          />
          <mesh
            name="Sphere 17"
            geometry={nodes['Sphere 17'].geometry}
            material={materials.firefly}
            castShadow
            receiveShadow
            position={[-1000.87, 50.5, 257.02]}
          />
          <mesh
            name="Ellipse 55"
            geometry={nodes['Ellipse 55'].geometry}
            material={materials['back ground']}
            castShadow
            receiveShadow
            position={[136.43, -157.82, -514.55]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={1}
          />
          <mesh
            name="Ellipse 3"
            geometry={nodes['Ellipse 3'].geometry}
            material={materials['back ground']}
            castShadow
            receiveShadow
            position={[-191.07, -155.28, 481.48]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={1}
          />
          <mesh
            name="Cylinder 75"
            geometry={nodes['Cylinder 75'].geometry}
            material={materials['lily pad']}
            castShadow
            receiveShadow
            position={[32.66, -152.68, 227.93]}
            rotation={[0, -0.57, 0]}
          />
          <mesh
            name="Cylinder 2"
            geometry={nodes['Cylinder 2'].geometry}
            material={materials['lily pad']}
            castShadow
            receiveShadow
            position={[589.37, -156.19, 37.06]}
          />

          <mesh
            name="Sphere 3"
            geometry={nodes['Sphere 3'].geometry}
            material={materials.firefly}
            castShadow
            receiveShadow
            position={[-113.38, 146.15, 257.02]}
          />

          <mesh
            name="Ellipse 2"
            geometry={nodes['Ellipse 2'].geometry}
            material={materials.dirt}
            castShadow
            receiveShadow
            position={[-189.05, -161.28, 746.09]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={1}
          />

          <directionalLight
            name="Directional Light"
            castShadow
            intensity={2.33}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-803.1775}
            shadow-camera-right={803.1775}
            shadow-camera-top={803.1775}
            shadow-camera-bottom={-803.1775}
            color="#c6b700"
            position={[-1.65, -3.16, 1822.22]}
          />

          <directionalLight
            name="Directional Light 2"
            castShadow
            intensity={3.08}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-50}
            shadow-camera-right={50}
            shadow-camera-top={50}
            shadow-camera-bottom={-50}
            color="#5c00c7"
            position={[-34.93, 653, -1340.89]}
          />

          <hemisphereLight name="Default Ambient Light" intensity={-1.54} color="#45436c" />
        </group>
      </animated.group>
    </>
  )
}
